### ISSUE TITLE
Ore pillager bug ?

### ISSUE THREAD

**Issue by FaultyPixel** [Globox1997/Inventory-FriendZ#1]
When crafting multiple ore pillager and linking one to an ore, others get linked to the same ore
Also, when relaunching a game, the ore pillager is no longer associated with it's ore.
Worth mentioning i'm on 1.15.2

**Comment by Globox1997** [comment]
thanks for the feedback, currently it is my intention to have only one pillager associated to an ore, so it is not worth to craft a second one. yea the relaunching bug is a problem, maybe I will be able fix it in the official 1.16 release
